#!/usr/bin/env python

import sys

def find_difference(s1, s2):
    l1=len(s1)
    l2=len(s2)

    if len(s1) != len(s2):
        return 0

    for l in range(l1):
        if s1[l] != s2[l]:
            return [s1,s2] if s1[l]=='1' else [s2,s1]

    sys.stderr.write("\nNo complementary read found for {}\n".format(s1))
    return 0


def main():
    reads = find_difference(sys.argv[1], sys.argv[2])

    if reads:
        sys.stdout.write("{}\t{}\n".format(reads[0], reads[1]))

if __name__ == '__main__':
    main()
